import type { Metadata } from "next";
import "@/styles/globals.css";
import RQProvider from "@/components/RQProvider";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "prography 11th frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={clsx("h-full min-h-dvh w-full")}>
        <RQProvider>{children}</RQProvider>
      </body>
    </html>
  );
}
